import js from "@eslint/js";
import vitest from "@vitest/eslint-plugin";
import { defineConfig } from "eslint/config";
import prettier from "eslint-config-prettier";
import functional from "eslint-plugin-functional";
import importX from "eslint-plugin-import-x";
import reactHooks from "eslint-plugin-react-hooks";
import globals from "globals";
import tseslint from "typescript-eslint";

export default defineConfig(
  {
    ignores: [
      "node_modules/**",
      ".wrangler/**",
      "dist/**",
      "cli/dist/**",
      "drizzle/**",
      // Generated by `pnpm db:generate:do` / `pnpm db:generate:event-log`
      // (drizzle-kit + the bundle codegen). DO SQLite migration bundles
      // — generated verbatim, never hand-edited (same model as
      // better-auth.ts below).
      "drizzle-do/**",
      "drizzle-event-log/**",
      "worker-configuration.d.ts",
      "corpus/**",
      "src/corpus/**",
      // Generated by the TanStack Router plugin; contains `as any` by
      // design. Excluded so it can't mask or break repo lint.
      "src/routeTree.gen.ts",
      // Generated verbatim by `npx auth@latest generate` (pnpm
      // auth:schema). Version-exact Better Auth Drizzle schema — never
      // hand-edited, so it must not be held to repo lint conventions.
      "src/control/schema/better-auth.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.worker,
        ...globals.node,
      },
      parserOptions: {
        // A dedicated lint tsconfig covers src + test + root config files
        // (the build tsconfig is intentionally src-only). This is what
        // lets test/ and *.config.ts be typed-linted at all.
        project: "./tsconfig.eslint.json",
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: { functional },
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      "@typescript-eslint/consistent-type-definitions": ["error", "type"],
      "@typescript-eslint/no-import-type-side-effects": "error",
      "@typescript-eslint/no-misused-promises": [
        "error",
        { checksVoidReturn: { attributes: false } },
      ],
      "@typescript-eslint/restrict-template-expressions": [
        "error",
        { allowNumber: true, allowBoolean: true, allowNullish: true },
      ],
      // `() => void promise()` fire-and-forget in event handlers is an
      // intentional, readable idiom here — not a confusing return.
      "@typescript-eslint/no-confusing-void-expression": [
        "error",
        { ignoreArrowShorthand: true },
      ],
      // TanStack Start control flow: `throw redirect(...)` / `notFound()`
      // throw framework objects that are not Error instances by design.
      "@typescript-eslint/only-throw-error": [
        "error",
        {
          allow: [
            {
              from: "package",
              package: "@tanstack/react-router",
              name: ["Redirect", "NotFoundError"],
            },
          ],
        },
      ],
      "no-console": "off",
      eqeqeq: ["error", "always", { null: "ignore" }],
      // Value/DTO types must be at least ReadonlyShallow. Excluded:
      // live library handles (a Drizzle client is not a frozen value) and
      // framework declaration-merging interfaces that MUST stay mutable
      // `interface`s (TanStack `Register`) or are external tuple aliases.
      "functional/type-declaration-immutability": [
        "error",
        {
          ignoreIdentifierPattern: ["^ControlDb$", "^LedgerDb$", "^Register$"],
          rules: [
            {
              identifiers: ".*",
              immutability: "ReadonlyShallow",
              comparator: "AtLeast",
              fixer: [
                {
                  pattern: "^(Array|Map|Set)<(.+)>$",
                  replace: "Readonly$1<$2>",
                },
                { pattern: "^(.+)$", replace: "Readonly<$1>" },
              ],
            },
          ],
        },
      ],
    },
  },
  // React hooks correctness (rules-of-hooks + exhaustive-deps) for the
  // TanStack Start UI and custom hooks in src/lib.
  {
    files: ["src/**/*.{ts,tsx}"],
    plugins: { "react-hooks": reactHooks },
    rules: reactHooks.configs.recommended.rules,
  },
  // Import hygiene. Scoped to order/cycle/dedup/default — NOT the
  // resolution family (no-unresolved/named/…): tsc already guarantees
  // those better, and enabling them only adds false positives on virtual
  // `cloudflare:*` modules. `no-cycle` is the real prize as entities grow.
  {
    files: ["**/*.{ts,tsx,js}"],
    plugins: { "import-x": importX },
    settings: {
      "import-x/resolver": {
        typescript: { project: "./tsconfig.eslint.json" },
        node: true,
      },
    },
    rules: {
      "import-x/order": [
        "error",
        {
          groups: [
            "builtin",
            "external",
            "internal",
            "parent",
            "sibling",
            "index",
          ],
          pathGroups: [{ pattern: "@/**", group: "internal" }],
          pathGroupsExcludedImportTypes: ["builtin"],
          "newlines-between": "always",
          alphabetize: { order: "asc", caseInsensitive: true },
        },
      ],
      "import-x/no-cycle": [
        "error",
        { maxDepth: Infinity, ignoreExternal: true },
      ],
      "import-x/no-duplicates": "error",
      "import-x/first": "error",
      "import-x/newline-after-import": "error",
      "import-x/no-default-export": "error",
    },
  },
  // Default export is the required contract for the Workers entry and
  // tool config files.
  {
    files: [
      "src/server.ts",
      "vite.config.ts",
      "drizzle.config.ts",
      "drizzle.do.config.ts",
      "drizzle.event-log.config.ts",
      "eslint.config.js",
    ],
    rules: { "import-x/no-default-export": "off" },
  },
  // TanStack loaders throw framework control-flow objects (`redirect()`,
  // `notFound()`) that are not Error instances by design.
  {
    files: ["src/routes/**/*.tsx"],
    rules: { "@typescript-eslint/only-throw-error": "off" },
  },
  // Test files: vitest correctness rules, plus relaxations for harness
  // code. Test code legitimately works against loosely-typed seams (DO
  // RPC stubs, `cloudflare:test` env, mocks); the type-safety strict
  // family is noise there, so keep logic/correctness rules and drop the
  // type-strictness ones (standard practice for typed-linted tests).
  {
    files: ["src/eval/**/*.ts", "test/**/*.ts"],
    plugins: { vitest },
    rules: {
      ...vitest.configs.recommended.rules,
      "vitest/no-focused-tests": "error",
      "vitest/no-conditional-expect": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unnecessary-condition": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/require-await": "off",
      "@typescript-eslint/dot-notation": "off",
      "@typescript-eslint/consistent-type-definitions": "off",
      "functional/type-declaration-immutability": "off",
    },
  },
  prettier,
);
