// GENERATED by `pnpm db:generate:do` — do not edit.
// Source of truth is the Drizzle schema in src/db.ts; this is the DO
// SQLite migration bundle consumed by drizzle-orm/durable-sqlite/migrator.

export type LedgerMigrationBundle = {
  journal: {
    entries: {
      idx: number;
      when: number;
      tag: string;
      breakpoints: boolean;
    }[];
  };
  migrations: Record<string, string>;
};

export const ledgerMigrations: LedgerMigrationBundle = {
  "journal": {
    "entries": [
      {
        "idx": 0,
        "when": 1779931491429,
        "tag": "0000_lovely_mastermind",
        "breakpoints": true
      }
    ]
  },
  "migrations": {
    "m0000": "CREATE TABLE `event_log` (\n\t`monotonic_id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`schema_version` integer NOT NULL,\n\t`project_id` text NOT NULL,\n\t`idempotency_key` text NOT NULL,\n\t`event_type` text NOT NULL,\n\t`timestamp` text NOT NULL,\n\t`payload` text NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `event_log_idempotency_key_unique` ON `event_log` (`idempotency_key`);"
  }
};
