// GENERATED by `pnpm db:generate:do` — do not edit.
// Source of truth is the Drizzle schema in src/db.ts; this is the DO
// SQLite migration bundle consumed by drizzle-orm/durable-sqlite/migrator.

export type LedgerMigrationBundle = {
  journal: {
    entries: {
      idx: number;
      when: number;
      tag: string;
      breakpoints: boolean;
    }[];
  };
  migrations: Record<string, string>;
};

export const ledgerMigrations: LedgerMigrationBundle = {
  "journal": {
    "entries": [
      {
        "idx": 0,
        "when": 1779931490611,
        "tag": "0000_lazy_blindfold",
        "breakpoints": true
      }
    ]
  },
  "migrations": {
    "m0000": "CREATE TABLE `change_events` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`event_type` text NOT NULL,\n\t`document_slug` text,\n\t`collection_slug` text,\n\t`before_json` text,\n\t`after_json` text,\n\t`changed_at` text NOT NULL,\n\t`changed_by` text NOT NULL\n);\n--> statement-breakpoint\nCREATE TABLE `content_blobs` (\n\t`hash` text PRIMARY KEY NOT NULL,\n\t`bytes` blob NOT NULL,\n\t`created_at` text NOT NULL\n);\n--> statement-breakpoint\nCREATE TABLE `instrumentation_outbox` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`local_event_id` integer NOT NULL,\n\t`schema_version` integer NOT NULL,\n\t`project_id` text NOT NULL,\n\t`idempotency_key` text NOT NULL,\n\t`event_type` text NOT NULL,\n\t`payload` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`attempt_count` integer DEFAULT 0 NOT NULL\n);\n"
  }
};
