// GENERATED by `pnpm db:generate:do` — do not edit.
// Source of truth is the Drizzle schema in src/db.ts; this is the DO
// SQLite migration bundle consumed by drizzle-orm/durable-sqlite/migrator.

export type LedgerMigrationBundle = {
  journal: {
    entries: {
      idx: number;
      when: number;
      tag: string;
      breakpoints: boolean;
    }[];
  };
  migrations: Record<string, string>;
};

export const ledgerMigrations: LedgerMigrationBundle = {
  "journal": {
    "entries": [
      {
        "idx": 0,
        "when": 1779931490611,
        "tag": "0000_lazy_blindfold",
        "breakpoints": true
      },
      {
        "idx": 1,
        "when": 1780851532592,
        "tag": "0001_shocking_vector",
        "breakpoints": true
      },
      {
        "idx": 2,
        "when": 1780854821390,
        "tag": "0002_true_black_bird",
        "breakpoints": true
      },
      {
        "idx": 3,
        "when": 1780876733721,
        "tag": "0003_clever_sunspot",
        "breakpoints": true
      }
    ]
  },
  "migrations": {
    "m0000": "CREATE TABLE `change_events` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`event_type` text NOT NULL,\n\t`document_slug` text,\n\t`collection_slug` text,\n\t`before_json` text,\n\t`after_json` text,\n\t`changed_at` text NOT NULL,\n\t`changed_by` text NOT NULL\n);\n--> statement-breakpoint\nCREATE TABLE `content_blobs` (\n\t`hash` text PRIMARY KEY NOT NULL,\n\t`bytes` blob NOT NULL,\n\t`created_at` text NOT NULL\n);\n--> statement-breakpoint\nCREATE TABLE `instrumentation_outbox` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`local_event_id` integer NOT NULL,\n\t`schema_version` integer NOT NULL,\n\t`project_id` text NOT NULL,\n\t`idempotency_key` text NOT NULL,\n\t`event_type` text NOT NULL,\n\t`payload` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`attempt_count` integer DEFAULT 0 NOT NULL\n);\n",
    "m0001": "CREATE TABLE `comment` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`thread_id` integer NOT NULL,\n\t`body` text NOT NULL,\n\t`created_by` text NOT NULL,\n\t`created_at` text NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `comment_thread_id` ON `comment` (`thread_id`);--> statement-breakpoint\nCREATE TABLE `comment_thread` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`document_slug` text NOT NULL,\n\t`anchor_block_id` text NOT NULL,\n\t`anchor_start` integer NOT NULL,\n\t`anchor_end` integer NOT NULL,\n\t`quote_prefix` text NOT NULL,\n\t`quote_exact` text NOT NULL,\n\t`quote_suffix` text NOT NULL,\n\t`status` text NOT NULL,\n\t`created_by` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`resolved_by` text,\n\t`resolved_at` text,\n\tCONSTRAINT \"comment_thread_status_valid\" CHECK(status in ('open', 'resolved', 'orphaned'))\n);\n--> statement-breakpoint\nCREATE INDEX `comment_thread_doc` ON `comment_thread` (`document_slug`);--> statement-breakpoint\nCREATE TABLE `document_block_map` (\n\t`document_slug` text NOT NULL,\n\t`doc_version` integer NOT NULL,\n\t`parser_version` integer NOT NULL,\n\t`blocks` text NOT NULL,\n\tPRIMARY KEY(`document_slug`, `doc_version`)\n);\n--> statement-breakpoint\nCREATE TABLE `document_block_seq` (\n\t`document_slug` text PRIMARY KEY NOT NULL,\n\t`next` integer DEFAULT 0 NOT NULL\n);\n",
    "m0002": "CREATE TABLE `suggestion` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`document_slug` text NOT NULL,\n\t`base_doc_version` integer NOT NULL,\n\t`proposed_markdown` text NOT NULL,\n\t`status` text NOT NULL,\n\t`created_by` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`resolved_by` text,\n\t`resolved_at` text,\n\tCONSTRAINT \"suggestion_status_valid\" CHECK(status in ('open', 'applied', 'rejected', 'stale'))\n);\n--> statement-breakpoint\nCREATE INDEX `suggestion_doc` ON `suggestion` (`document_slug`);--> statement-breakpoint\nCREATE TABLE `suggestion_hunk` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`suggestion_id` integer NOT NULL,\n\t`ordinal` integer NOT NULL,\n\t`op` text NOT NULL,\n\t`base_start` integer NOT NULL,\n\t`base_end` integer NOT NULL,\n\t`proposed_text` text NOT NULL,\n\t`decision` text NOT NULL,\n\tCONSTRAINT \"suggestion_hunk_op_valid\" CHECK(op in ('replace', 'insert', 'delete')),\n\tCONSTRAINT \"suggestion_hunk_decision_valid\" CHECK(decision in ('pending', 'accepted', 'rejected'))\n);\n--> statement-breakpoint\nCREATE INDEX `suggestion_hunk_suggestion` ON `suggestion_hunk` (`suggestion_id`);",
    "m0003": "ALTER TABLE `suggestion` ADD `channel` text DEFAULT 'web' NOT NULL;"
  }
};
