// Shared bundle logic for the DO SQLite ledger migrations, so the
// generator (`bundle-do-migrations.ts`) and the drift check
// (`check-do-migrations.ts`) reshape drizzle-kit output identically —
// a single definition of the `migrate()` config format.

import { readFile } from "node:fs/promises";
import { join } from "node:path";

type JournalEntry = Readonly<{
  idx: number;
  when: number;
  tag: string;
  breakpoints: boolean;
}>;

// Build the typed `migrations.ts` source from a drizzle-kit output dir
// (its `meta/_journal.json` + each `<tag>.sql`), with the SQL inlined so
// the bundle needs no `.sql` text-import loader in any environment.
export async function buildBundleSource(dir: string): Promise<string> {
  const journal = JSON.parse(
    await readFile(join(dir, "meta", "_journal.json"), "utf8"),
  ) as { entries: readonly JournalEntry[] };

  const migrations: Record<string, string> = {};
  for (const entry of journal.entries) {
    // Key format the durable-sqlite migrator looks up.
    const key = `m${entry.idx.toString().padStart(4, "0")}`;
    migrations[key] = await readFile(join(dir, `${entry.tag}.sql`), "utf8");
  }

  const payload = JSON.stringify(
    {
      journal: {
        entries: journal.entries.map((e) => ({
          idx: e.idx,
          when: e.when,
          tag: e.tag,
          breakpoints: e.breakpoints,
        })),
      },
      migrations,
    },
    null,
    2,
  );

  return `// GENERATED by \`pnpm db:generate:do\` — do not edit.
// Source of truth is the Drizzle schema in src/db.ts; this is the DO
// SQLite migration bundle consumed by drizzle-orm/durable-sqlite/migrator.

export type LedgerMigrationBundle = {
  journal: {
    entries: {
      idx: number;
      when: number;
      tag: string;
      breakpoints: boolean;
    }[];
  };
  migrations: Record<string, string>;
};

export const ledgerMigrations: LedgerMigrationBundle = ${payload};
`;
}
