/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as ConnectSelectRouteImport } from './routes/connect.select'
import { Route as InviteInvitationIdRouteImport } from './routes/invite.$invitationId'
import { Route as PProjectIdRouteRouteImport } from './routes/p/$projectId/route'
import { Route as PProjectIdIndexRouteImport } from './routes/p/$projectId/index'
import { Route as PProjectIdChangesRouteImport } from './routes/p/$projectId/changes'
import { Route as PProjectIdImportRouteImport } from './routes/p/$projectId/import'
import { Route as PProjectIdSettingsRouteImport } from './routes/p/$projectId/settings'
import { Route as PProjectIdTeamRouteImport } from './routes/p/$projectId/team'
import { Route as PProjectIdCollectionsIndexRouteImport } from './routes/p/$projectId/collections/index'
import { Route as PProjectIdCollectionsSlugRouteImport } from './routes/p/$projectId/collections/$slug'
import { Route as PProjectIdDocumentsIndexRouteImport } from './routes/p/$projectId/documents/index'
import { Route as PProjectIdDocumentsSlugRouteRouteImport } from './routes/p/$projectId/documents/$slug/route'
import { Route as PProjectIdDocumentsNewRouteImport } from './routes/p/$projectId/documents/new'
import { Route as PProjectIdCollectionsSlugActivityRouteImport } from './routes/p/$projectId/collections/$slug_.activity'
import { Route as PProjectIdConnectorsMcpSetupRouteImport } from './routes/p/$projectId/connectors/mcp/setup'
import { Route as PProjectIdDocumentsSlugIndexRouteImport } from './routes/p/$projectId/documents/$slug/index'
import { Route as PProjectIdDocumentsSlugVersionsRouteImport } from './routes/p/$projectId/documents/$slug/versions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ConnectSelectRoute = ConnectSelectRouteImport.update({
  id: '/connect/select',
  path: '/connect/select',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteInvitationIdRoute = InviteInvitationIdRouteImport.update({
  id: '/invite/$invitationId',
  path: '/invite/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdRouteRoute = PProjectIdRouteRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdIndexRoute = PProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectIdRouteRoute,
} as any)
const PProjectIdChangesRoute = PProjectIdChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => PProjectIdRouteRoute,
} as any)
const PProjectIdImportRoute = PProjectIdImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => PProjectIdRouteRoute,
} as any)
const PProjectIdSettingsRoute = PProjectIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PProjectIdRouteRoute,
} as any)
const PProjectIdTeamRoute = PProjectIdTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => PProjectIdRouteRoute,
} as any)
const PProjectIdCollectionsIndexRoute =
  PProjectIdCollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => PProjectIdRouteRoute,
  } as any)
const PProjectIdCollectionsSlugRoute =
  PProjectIdCollectionsSlugRouteImport.update({
    id: '/collections/$slug',
    path: '/collections/$slug',
    getParentRoute: () => PProjectIdRouteRoute,
  } as any)
const PProjectIdDocumentsIndexRoute =
  PProjectIdDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => PProjectIdRouteRoute,
  } as any)
const PProjectIdDocumentsSlugRouteRoute =
  PProjectIdDocumentsSlugRouteRouteImport.update({
    id: '/documents/$slug',
    path: '/documents/$slug',
    getParentRoute: () => PProjectIdRouteRoute,
  } as any)
const PProjectIdDocumentsNewRoute = PProjectIdDocumentsNewRouteImport.update({
  id: '/documents/new',
  path: '/documents/new',
  getParentRoute: () => PProjectIdRouteRoute,
} as any)
const PProjectIdCollectionsSlugActivityRoute =
  PProjectIdCollectionsSlugActivityRouteImport.update({
    id: '/collections/$slug_/activity',
    path: '/collections/$slug/activity',
    getParentRoute: () => PProjectIdRouteRoute,
  } as any)
const PProjectIdConnectorsMcpSetupRoute =
  PProjectIdConnectorsMcpSetupRouteImport.update({
    id: '/connectors/mcp/setup',
    path: '/connectors/mcp/setup',
    getParentRoute: () => PProjectIdRouteRoute,
  } as any)
const PProjectIdDocumentsSlugIndexRoute =
  PProjectIdDocumentsSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PProjectIdDocumentsSlugRouteRoute,
  } as any)
const PProjectIdDocumentsSlugVersionsRoute =
  PProjectIdDocumentsSlugVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => PProjectIdDocumentsSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/consent': typeof ConsentRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/p/$projectId': typeof PProjectIdRouteRouteWithChildren
  '/admin/projects': typeof AdminProjectsRoute
  '/connect/select': typeof ConnectSelectRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/admin/': typeof AdminIndexRoute
  '/p/$projectId/changes': typeof PProjectIdChangesRoute
  '/p/$projectId/import': typeof PProjectIdImportRoute
  '/p/$projectId/settings': typeof PProjectIdSettingsRoute
  '/p/$projectId/team': typeof PProjectIdTeamRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
  '/p/$projectId/documents/$slug': typeof PProjectIdDocumentsSlugRouteRouteWithChildren
  '/p/$projectId/collections/$slug': typeof PProjectIdCollectionsSlugRoute
  '/p/$projectId/documents/new': typeof PProjectIdDocumentsNewRoute
  '/p/$projectId/collections/': typeof PProjectIdCollectionsIndexRoute
  '/p/$projectId/documents/': typeof PProjectIdDocumentsIndexRoute
  '/p/$projectId/collections/$slug/activity': typeof PProjectIdCollectionsSlugActivityRoute
  '/p/$projectId/connectors/mcp/setup': typeof PProjectIdConnectorsMcpSetupRoute
  '/p/$projectId/documents/$slug/versions': typeof PProjectIdDocumentsSlugVersionsRoute
  '/p/$projectId/documents/$slug/': typeof PProjectIdDocumentsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/consent': typeof ConsentRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/connect/select': typeof ConnectSelectRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/admin': typeof AdminIndexRoute
  '/p/$projectId/changes': typeof PProjectIdChangesRoute
  '/p/$projectId/import': typeof PProjectIdImportRoute
  '/p/$projectId/settings': typeof PProjectIdSettingsRoute
  '/p/$projectId/team': typeof PProjectIdTeamRoute
  '/p/$projectId': typeof PProjectIdIndexRoute
  '/p/$projectId/collections/$slug': typeof PProjectIdCollectionsSlugRoute
  '/p/$projectId/documents/new': typeof PProjectIdDocumentsNewRoute
  '/p/$projectId/collections': typeof PProjectIdCollectionsIndexRoute
  '/p/$projectId/documents': typeof PProjectIdDocumentsIndexRoute
  '/p/$projectId/collections/$slug/activity': typeof PProjectIdCollectionsSlugActivityRoute
  '/p/$projectId/connectors/mcp/setup': typeof PProjectIdConnectorsMcpSetupRoute
  '/p/$projectId/documents/$slug/versions': typeof PProjectIdDocumentsSlugVersionsRoute
  '/p/$projectId/documents/$slug': typeof PProjectIdDocumentsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/consent': typeof ConsentRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/p/$projectId': typeof PProjectIdRouteRouteWithChildren
  '/admin/projects': typeof AdminProjectsRoute
  '/connect/select': typeof ConnectSelectRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/admin/': typeof AdminIndexRoute
  '/p/$projectId/changes': typeof PProjectIdChangesRoute
  '/p/$projectId/import': typeof PProjectIdImportRoute
  '/p/$projectId/settings': typeof PProjectIdSettingsRoute
  '/p/$projectId/team': typeof PProjectIdTeamRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
  '/p/$projectId/documents/$slug': typeof PProjectIdDocumentsSlugRouteRouteWithChildren
  '/p/$projectId/collections/$slug': typeof PProjectIdCollectionsSlugRoute
  '/p/$projectId/documents/new': typeof PProjectIdDocumentsNewRoute
  '/p/$projectId/collections/': typeof PProjectIdCollectionsIndexRoute
  '/p/$projectId/documents/': typeof PProjectIdDocumentsIndexRoute
  '/p/$projectId/collections/$slug_/activity': typeof PProjectIdCollectionsSlugActivityRoute
  '/p/$projectId/connectors/mcp/setup': typeof PProjectIdConnectorsMcpSetupRoute
  '/p/$projectId/documents/$slug/versions': typeof PProjectIdDocumentsSlugVersionsRoute
  '/p/$projectId/documents/$slug/': typeof PProjectIdDocumentsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/$'
    | '/consent'
    | '/sign-in'
    | '/sign-up'
    | '/p/$projectId'
    | '/admin/projects'
    | '/connect/select'
    | '/invite/$invitationId'
    | '/admin/'
    | '/p/$projectId/changes'
    | '/p/$projectId/import'
    | '/p/$projectId/settings'
    | '/p/$projectId/team'
    | '/p/$projectId/'
    | '/p/$projectId/documents/$slug'
    | '/p/$projectId/collections/$slug'
    | '/p/$projectId/documents/new'
    | '/p/$projectId/collections/'
    | '/p/$projectId/documents/'
    | '/p/$projectId/collections/$slug/activity'
    | '/p/$projectId/connectors/mcp/setup'
    | '/p/$projectId/documents/$slug/versions'
    | '/p/$projectId/documents/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/consent'
    | '/sign-in'
    | '/sign-up'
    | '/admin/projects'
    | '/connect/select'
    | '/invite/$invitationId'
    | '/admin'
    | '/p/$projectId/changes'
    | '/p/$projectId/import'
    | '/p/$projectId/settings'
    | '/p/$projectId/team'
    | '/p/$projectId'
    | '/p/$projectId/collections/$slug'
    | '/p/$projectId/documents/new'
    | '/p/$projectId/collections'
    | '/p/$projectId/documents'
    | '/p/$projectId/collections/$slug/activity'
    | '/p/$projectId/connectors/mcp/setup'
    | '/p/$projectId/documents/$slug/versions'
    | '/p/$projectId/documents/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/$'
    | '/consent'
    | '/sign-in'
    | '/sign-up'
    | '/p/$projectId'
    | '/admin/projects'
    | '/connect/select'
    | '/invite/$invitationId'
    | '/admin/'
    | '/p/$projectId/changes'
    | '/p/$projectId/import'
    | '/p/$projectId/settings'
    | '/p/$projectId/team'
    | '/p/$projectId/'
    | '/p/$projectId/documents/$slug'
    | '/p/$projectId/collections/$slug'
    | '/p/$projectId/documents/new'
    | '/p/$projectId/collections/'
    | '/p/$projectId/documents/'
    | '/p/$projectId/collections/$slug_/activity'
    | '/p/$projectId/connectors/mcp/setup'
    | '/p/$projectId/documents/$slug/versions'
    | '/p/$projectId/documents/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  ConsentRoute: typeof ConsentRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  PProjectIdRouteRoute: typeof PProjectIdRouteRouteWithChildren
  ConnectSelectRoute: typeof ConnectSelectRoute
  InviteInvitationIdRoute: typeof InviteInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/connect/select': {
      id: '/connect/select'
      path: '/connect/select'
      fullPath: '/connect/select'
      preLoaderRoute: typeof ConnectSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$invitationId': {
      id: '/invite/$invitationId'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof InviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId': {
      id: '/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof PProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/': {
      id: '/p/$projectId/'
      path: '/'
      fullPath: '/p/$projectId/'
      preLoaderRoute: typeof PProjectIdIndexRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/changes': {
      id: '/p/$projectId/changes'
      path: '/changes'
      fullPath: '/p/$projectId/changes'
      preLoaderRoute: typeof PProjectIdChangesRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/import': {
      id: '/p/$projectId/import'
      path: '/import'
      fullPath: '/p/$projectId/import'
      preLoaderRoute: typeof PProjectIdImportRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/settings': {
      id: '/p/$projectId/settings'
      path: '/settings'
      fullPath: '/p/$projectId/settings'
      preLoaderRoute: typeof PProjectIdSettingsRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/team': {
      id: '/p/$projectId/team'
      path: '/team'
      fullPath: '/p/$projectId/team'
      preLoaderRoute: typeof PProjectIdTeamRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/collections/': {
      id: '/p/$projectId/collections/'
      path: '/collections'
      fullPath: '/p/$projectId/collections/'
      preLoaderRoute: typeof PProjectIdCollectionsIndexRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/collections/$slug': {
      id: '/p/$projectId/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/p/$projectId/collections/$slug'
      preLoaderRoute: typeof PProjectIdCollectionsSlugRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/documents/': {
      id: '/p/$projectId/documents/'
      path: '/documents'
      fullPath: '/p/$projectId/documents/'
      preLoaderRoute: typeof PProjectIdDocumentsIndexRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/documents/$slug': {
      id: '/p/$projectId/documents/$slug'
      path: '/documents/$slug'
      fullPath: '/p/$projectId/documents/$slug'
      preLoaderRoute: typeof PProjectIdDocumentsSlugRouteRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/documents/new': {
      id: '/p/$projectId/documents/new'
      path: '/documents/new'
      fullPath: '/p/$projectId/documents/new'
      preLoaderRoute: typeof PProjectIdDocumentsNewRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/collections/$slug_/activity': {
      id: '/p/$projectId/collections/$slug_/activity'
      path: '/collections/$slug/activity'
      fullPath: '/p/$projectId/collections/$slug/activity'
      preLoaderRoute: typeof PProjectIdCollectionsSlugActivityRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/connectors/mcp/setup': {
      id: '/p/$projectId/connectors/mcp/setup'
      path: '/connectors/mcp/setup'
      fullPath: '/p/$projectId/connectors/mcp/setup'
      preLoaderRoute: typeof PProjectIdConnectorsMcpSetupRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/documents/$slug/': {
      id: '/p/$projectId/documents/$slug/'
      path: '/'
      fullPath: '/p/$projectId/documents/$slug/'
      preLoaderRoute: typeof PProjectIdDocumentsSlugIndexRouteImport
      parentRoute: typeof PProjectIdDocumentsSlugRouteRoute
    }
    '/p/$projectId/documents/$slug/versions': {
      id: '/p/$projectId/documents/$slug/versions'
      path: '/versions'
      fullPath: '/p/$projectId/documents/$slug/versions'
      preLoaderRoute: typeof PProjectIdDocumentsSlugVersionsRouteImport
      parentRoute: typeof PProjectIdDocumentsSlugRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminProjectsRoute: AdminProjectsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PProjectIdDocumentsSlugRouteRouteChildren {
  PProjectIdDocumentsSlugVersionsRoute: typeof PProjectIdDocumentsSlugVersionsRoute
  PProjectIdDocumentsSlugIndexRoute: typeof PProjectIdDocumentsSlugIndexRoute
}

const PProjectIdDocumentsSlugRouteRouteChildren: PProjectIdDocumentsSlugRouteRouteChildren =
  {
    PProjectIdDocumentsSlugVersionsRoute: PProjectIdDocumentsSlugVersionsRoute,
    PProjectIdDocumentsSlugIndexRoute: PProjectIdDocumentsSlugIndexRoute,
  }

const PProjectIdDocumentsSlugRouteRouteWithChildren =
  PProjectIdDocumentsSlugRouteRoute._addFileChildren(
    PProjectIdDocumentsSlugRouteRouteChildren,
  )

interface PProjectIdRouteRouteChildren {
  PProjectIdChangesRoute: typeof PProjectIdChangesRoute
  PProjectIdImportRoute: typeof PProjectIdImportRoute
  PProjectIdSettingsRoute: typeof PProjectIdSettingsRoute
  PProjectIdTeamRoute: typeof PProjectIdTeamRoute
  PProjectIdIndexRoute: typeof PProjectIdIndexRoute
  PProjectIdDocumentsSlugRouteRoute: typeof PProjectIdDocumentsSlugRouteRouteWithChildren
  PProjectIdCollectionsSlugRoute: typeof PProjectIdCollectionsSlugRoute
  PProjectIdDocumentsNewRoute: typeof PProjectIdDocumentsNewRoute
  PProjectIdCollectionsIndexRoute: typeof PProjectIdCollectionsIndexRoute
  PProjectIdDocumentsIndexRoute: typeof PProjectIdDocumentsIndexRoute
  PProjectIdCollectionsSlugActivityRoute: typeof PProjectIdCollectionsSlugActivityRoute
  PProjectIdConnectorsMcpSetupRoute: typeof PProjectIdConnectorsMcpSetupRoute
}

const PProjectIdRouteRouteChildren: PProjectIdRouteRouteChildren = {
  PProjectIdChangesRoute: PProjectIdChangesRoute,
  PProjectIdImportRoute: PProjectIdImportRoute,
  PProjectIdSettingsRoute: PProjectIdSettingsRoute,
  PProjectIdTeamRoute: PProjectIdTeamRoute,
  PProjectIdIndexRoute: PProjectIdIndexRoute,
  PProjectIdDocumentsSlugRouteRoute:
    PProjectIdDocumentsSlugRouteRouteWithChildren,
  PProjectIdCollectionsSlugRoute: PProjectIdCollectionsSlugRoute,
  PProjectIdDocumentsNewRoute: PProjectIdDocumentsNewRoute,
  PProjectIdCollectionsIndexRoute: PProjectIdCollectionsIndexRoute,
  PProjectIdDocumentsIndexRoute: PProjectIdDocumentsIndexRoute,
  PProjectIdCollectionsSlugActivityRoute:
    PProjectIdCollectionsSlugActivityRoute,
  PProjectIdConnectorsMcpSetupRoute: PProjectIdConnectorsMcpSetupRoute,
}

const PProjectIdRouteRouteWithChildren = PProjectIdRouteRoute._addFileChildren(
  PProjectIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  ConsentRoute: ConsentRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  PProjectIdRouteRoute: PProjectIdRouteRouteWithChildren,
  ConnectSelectRoute: ConnectSelectRoute,
  InviteInvitationIdRoute: InviteInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
